# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

nname: Build and deploy JAR app to Azure Web App - robin-spring-boot-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_VERSION: '25'
  APP_NAME: 'robin-spring-boot-app'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'
          cache: 'maven'

      - name: Build with Maven (from /demo folder)
        run: mvn clean package -DskipTests
        working-directory: demo

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE1DEC9EF79042B29270F79126596F5B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_858D4B8D13304EBD8F43F6AC80E74B23 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B6EED53E1594024A0C352474CF753BD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          package: demo/target/*.jar
          